@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

Class "{abstract}\nCommand" as Command
Class "{abstract}\nEditCommand" as EditCommand
Class "EditPersonCommand" as EditPersonCommand
Class "EditItineraryCommand" as EditItineraryCommand
Class "EditPersonDescriptor" as EditPersonDescriptor
Class "EditItineraryDescriptor" as EditItineraryDescriptor
Class "<<interface>>\nModel" as Model
Class "Person" as Person
Class "Itinerary" as Itinerary
Class "CommandResult" as CommandResult

Command <|-- EditCommand
EditCommand <|-- EditPersonCommand
EditCommand <|-- EditItineraryCommand
EditPersonCommand --> EditPersonDescriptor
EditItineraryCommand --> EditItineraryDescriptor
EditCommand --> Model
EditCommand --> CommandResult
Model --> Person
Model --> Itinerary

note bottom of EditPersonDescriptor
Contained within EditPersonCommand
end note

note bottom of EditItineraryDescriptor
Contained within EditItineraryCommand
end note

@enduml
