@startuml
!include style.puml
hide footbox

box Logic LOGIC_COLOR_T1
participant ":EditCommandParser" as parser LOGIC_COLOR
participant ":EditXYZDescriptor" as descriptor LOGIC_COLOR
participant ":EditXYZCommand" as command LOGIC_COLOR
end box

participant ":Model" as model MODEL_COLOR

[-> parser : parse("FLAG INDEX FIELD")
activate parser
note right: FLAG is either `/contact` or `/itinerary`, which specifies the type \nof entry being edited (`Person` or `Itinerary' respectively).\n INDEX specifies the target entry being edited. \n FIELD specifies the fields being edited.

parser -> parser : tokenize by prefixes
note right: Splits "INDEX FIELD" into\n index and field parameters

parser -> descriptor ** : new EditXYZDescriptor()
note right: `XYZ` is a placeholder for the type of entry \n being edited (either `Person` or 'Itinerary`)

parser -> parser : Parse and set values for \n edited fields in descriptor

parser -> parser : isAnyFieldEdited()

parser -> command ** : new EditXYZCommand(index, descriptor)

[<-- parser : command
deactivate parser

...

[-> command : execute(model)
activate command

command -> model : getFilteredXYZList()
activate model
model --> command
deactivate model

command -> command : createEditedXYZ()
note right: Merges original fields\n with descriptor values

alt duplicate entry
    [<-- command : throw CommandException
else valid edit
    command -> model : setXYZ(original, edited)
    activate model
    deactivate model

    command -> model : updateFilteredXYZList()
    activate model
    deactivate model

    [<-- command : CommandResult
end

deactivate command

@enduml
